semi = true
tabWidth = 4
useTabs = true
singleQuote = true
printWidth = 100
trailingComma = "none"
arrowParens = "avoid"
bracketSpacing = true
bracketSameLine = false
endOfLine = "lf"
vueIndentScriptAndStyle = true
singleAttributePerLine = true